ДЗ 1
have2go/2024-2-VK-EDU-Frontend-A-Degtyarev pull request #1
Opened 2024-09-22 22:13 UTC by have2go

# Домашнее задание №1

Прошу @martinkomitsky, @haseprogram, @kgrechin или @sh4rkizz проверить его.

Что было сделано:
* Были написаны функции nonUniqueElements и convertBytesToHuman
* Тест на функцию convertBytesToHuman

2024-09-22 22:37 UTC, sh4rkizz requested changes

2024-09-22 22:37 UTC, sh4rkizz commented on nonUniqueElements.js
> +    });
Использование дополнительного массива излишне
Попробуй применить какой-нибудь встроенный метод для фильтрации исходного массива

2024-09-22 22:37 UTC, sh4rkizz commented on convertBytesToHuman.js
> +    };
Давай попробуем решить задачу без хардкоженных величин для всех-всех единиц измерения

Текущее решение плохо масштабируется при увеличении числа возможных вариантов 
[петабайты, йоттабайты и тд]

2024-09-22 22:37 UTC, sh4rkizz commented on convertBytesToHuman.test.js
> +});
Было бы полезно [для выработки привычки] дополнить тесты и другими проверками 
например, `Infinity`, `() => {`}, `NaN`

2024-09-22 22:37 UTC, sh4rkizz commented
Следует также добавить преподов в `asingee`/`reviewers`, согласно инструкции сдачи домашек

2024-09-23 12:24 UTC, have2go commented
> Следует также добавить преподов в `asingee`/`reviewers`, согласно инструкции сдачи домашек

К сожалению, Мартин и Дмитрий пока не принимают мой инвайт(
На лекции они сказали не дожидаться и закидывать пул реквест. А так я периодически проверяю, обязательно добавлю.

2024-09-23 13:15 UTC, sh4rkizz approved these changes
LGTM

2024-09-25 21:04 UTC, HaseProgram approved these changes
12!

2024-09-25 21:04 UTC, merged