ДЗ 11
have2go/2024-2-VK-EDU-Frontend-A-Degtyarev pull request #11
Opened 2024-12-05 19:22 UTC by have2go

# Домашнее задание №11

Прошу @martinkomitsky, @haseprogram, @kgrechin или @sh4rkizz проверить его.

Что было сделано:
* Компонент LazyImage, с помощью IntersectionObserver картинка подгружается только если как минимум 10% её площади находятся в поле зрения
* Все фото в приложении заменены на LazyImage
* Добавил бесконечный скролл в списке чатов
* Вывел в toastify уведомления об удалении профиля/сохранении изменений
* Стилизовал тег <audio> для Firefox
![image](https://github.com/user-attachments/assets/76edb4cb-ff20-4d91-be29-1ec562f67556)

2024-12-06 12:58 UTC, sh4rkizz requested changes
рекомендации дал в личке

2024-12-08 18:13 UTC, sh4rkizz submitted a review, later dismissed
lgtm !

2024-12-08 18:13 UTC, sh4rkizz approved these changes
lgtm v2 !!!

2024-12-09 11:10 UTC, merged

2024-12-09 11:10 UTC, martinkomitsky commented
12!