Экзамен на проверку
have2go/2024-2-VK-EDU-Frontend-A-Degtyarev pull request #15
Opened 2024-12-23 18:29 UTC by have2go

- [x] В корневой папке репозитория создать базовое приложение `exam` с помощью [CRA](https://github.com/facebook/create-react-app#quick-overview) (или vite) по инструкции выше
- [x] Сверстать 2 страницы и необходимые компоненты
- [x] Использовать стили. Дизайн должен быть похожим на макет
- [x] Реализовать перевод с одного языка на другой (нужно сделать так, чтобы можно было выбирать языки из выпадающего списка)
- [ ] Реализовать перевод с неизвестного языка (автоопределитель из `API`)
- [x] Сохранять историю переводов в `localStorage`
- [x] Использовать `Redux`
- [x] Использовать `React-router` для перехода между страницами
- [ ] Задеплоить решение, используя `GitHub Actions`
- [ ] Ревью: получить правки по коду и исправить их (получаются лично у преподавателя и выполняются самостоятельно) [10 баллов]

2024-12-30 11:57 UTC, HaseProgram requested changes, later dismissed
Привет! Все классно! Аппрув точно. 
Но нашел баг (связанный с тем как ты хранишь данные в локал сторадже).

1) Ты сделал перевод (он сохранился в лс)
2) Ты поменял язык, с которого ты переводишь
3) Перевел еще раз (он ПЕРЕзатирает первый сохраненный вариант в лс)
4) При перезагрузке не вся история показывается.

Ставлю 42 балла, если поправишь баг, будет 46.

А еще у тебя был один бонусный балл, заработанный во время лекций, поэтому суммарно 43, а может быть 47)

2024-12-30 11:57 UTC, HaseProgram commented on exam/src/pages/Translator/Translator.tsx
> +        )?.code;
Возможно это можно вынести в useMemo, микрооптимизация)

2024-12-31 14:58 UTC, have2go commented
> Привет! Все классно! Аппрув точно. Но нашел баг (связанный с тем как ты хранишь данные в локал сторадже).
> 
> 1. Ты сделал перевод (он сохранился в лс)
> 2. Ты поменял язык, с которого ты переводишь
> 3. Перевел еще раз (он ПЕРЕзатирает первый сохраненный вариант в лс)
> 4. При перезагрузке не вся история показывается.
> 
> Ставлю 42 балла, если поправишь баг, будет 46.
> 
> А еще у тебя был один бонусный балл, заработанный во время лекций, поэтому суммарно 43, а может быть 47)

Поправил!
Теперь кэш и история хранятся в localStorage отдельно.

2024-12-31 15:01 UTC, have2go commented on exam/src/pages/Translator/Translator.tsx
> +        )?.code;
Вынес функцию в useMemo().
Я потестил её выводами в консоль — и правда без смены языка код внутри теперь не выполняется, круто)

2025-01-17 09:50 UTC, martinkomitsky approved these changes
47!

2025-01-17 09:51 UTC, merged