ДЗ 2
have2go/2024-2-VK-EDU-Frontend-A-Degtyarev pull request #2
Opened 2024-09-27 19:06 UTC by have2go

# Домашнее задание №2

Прошу @martinkomitsky, @haseprogram, @kgrechin или @sh4rkizz проверить его.

Что было сделано:
* Оформление сделал наподобие Material Web от гугла: https://material-web.dev/, надеюсь проверяющим понравится)
* Логика добавления новых сообщений
* Хранение сообщений и информации о времени создания и авторе в localstorage

![Снимок экрана 2024-09-27 211755](https://github.com/user-attachments/assets/c79944f8-ae87-4b1f-b0f3-fa0af2de29ea)
![Снимок экрана 2024-09-27 212145](https://github.com/user-attachments/assets/fc8ab80c-9bef-4826-9965-2bf1bea7254b)

2024-09-28 17:10 UTC, sh4rkizz requested changes
Привет, классно реализовал, мне понравился твой околореактовый подход и в целом хорошее понимание блочной верстки)
Есть несколько комментов

Для начала - предлагаю завести корневой .gitignore

2024-09-28 17:10 UTC, sh4rkizz commented on simple-chat/src/index.js
> +}
Использование этого метода в целом в домашке мне не очень понятно, хоть он и лежал по умолчанию в simple-chat 

Форма и так [при наличии фокуса в ней выполняет submit на нажатие кнопки `Enter`]
А этот метод еще и страницу ререндерит при отправке, что похоже на нежелательное поведение

2024-09-28 17:10 UTC, sh4rkizz commented on simple-chat/src/index.js
> +render();
Было бы интересно увидеть обработку отправки сообщений от собеседника [блоки сообщений от собеседника], если получится, предлагаю настроить через небольшой таймаут [0.5s - 1s]

2024-09-28 17:10 UTC, sh4rkizz commented on simple-chat/src/index.js
> +        render();
Хотелось бы иметь автоскролл до нижней части диалога при отправке сообщения

2024-09-28 17:10 UTC, sh4rkizz commented on simple-chat/src/index.html
> +            </form>
Также хотелось бы видеть какие-то кнопки, которые отправляют сообщения
Сейчас мы строгаем mobile-first, поэтому однозначно нужна кнопка отправки сообщения

2024-09-28 17:10 UTC, sh4rkizz commented on simple-chat/src/index.html
> +            </form>
Кстати про mobile-first, насколько я знаю, важно будет в будущем организовать адаптив для десктопа, стоит иметь ввиду уже сейчас

2024-09-28 17:10 UTC, sh4rkizz commented on simple-chat/src/index.js
> +        <p class="message__text">${obj.message}</p>
По идее, мне как отправителю не нужно видеть свое имя, имхо лишняя загруженность блока, но здесь со мной можно поспорить)

<img width="165" alt="изображение" src="https://github.com/user-attachments/assets/7d72137b-8a5b-4823-a817-03352c10a235">

2024-09-28 17:10 UTC, sh4rkizz commented on simple-chat/src/index.js
> +            <p class="message__time">${obj.createdAt}</p>
Давай сделаем прикольную штуку - title / tooltip, чтобы при наведении показывал полную дату
Референс из ТГ
<img width="171" alt="изображение" src="https://github.com/user-attachments/assets/b5671760-074b-46d1-8671-06e0076d1d3c">

2024-09-28 17:10 UTC, sh4rkizz commented on simple-chat/src/index.js
> +        localStorage.setItem("messageArr", JSON.stringify(messagesToRender));
Как элемент кодстайла, предлагаю переносить переиспользуемые строки в отдельные константы и определять их один раз, например `MESSAGE_LIST_KEY = "messageArr";`

2024-09-30 10:46 UTC, have2go commented on simple-chat/src/index.js
> +render();
У меня было несколько предположений, что именно тут нужно сделать, но т.к. пока не знаю как именно мы будем общаться с сервером для получения сообщений от собеседника, сделал так: добавил кнопку для имитации отправки сообщений собеседником, при нажатии сообщение добавляется в массив newMessages, а уже setInterval() раз в полсекунды смотрит, есть ли новые сообщения. Если да, добавляем их в messagesToRender, а newMessages очищаем. И чтобы не было потенциальных ошибок с очередностью сообщений, сортирую messagesToRender по дате создания.
![image](https://github.com/user-attachments/assets/a276f95d-14f2-4456-af2f-72b44bc0e363)

2024-09-30 16:47 UTC, sh4rkizz approved these changes
lgtm!

2024-10-01 21:26 UTC, HaseProgram approved these changes
Класс! 12!

2024-10-01 21:26 UTC, merged