ДЗ_3 на проверку
have2go/2024-2-VK-EDU-Frontend-A-Degtyarev pull request #3
Opened 2024-10-07 09:13 UTC by have2go

# Домашнее задание №3

Прошу @martinkomitsky, @haseprogram, @kgrechin или @sh4rkizz проверить его.

Что было сделано:
* Страница "Список чатов"
* Отображение информации о чате (статус прочитано\не прочитано, упоминания, количество новых сообщений)
* Для удобства разбил страницы и относящиеся к ним файлы в разные папки. Готов к переезду на реакт и разбивке страниц на компоненты.

2024-10-07 14:31 UTC, sh4rkizz requested changes
В целом гуд, но предлагаю избавиться от хардкода, сделать более динамично для пользователя

2024-10-07 14:31 UTC, sh4rkizz commented on simple-chat/src/index.js
> +const sampleUsers = [
Предлагаю отказаться от хардкода в пользу забора чатиков из localStorage

2024-10-07 14:31 UTC, sh4rkizz commented on simple-chat/src/index.js
> +                }
этот блок кода довольно тяжело читать из-за большого количества тернарных if-ов, обычно в таких случаях переносят сбор в отдельный компонент

2024-10-07 14:31 UTC, sh4rkizz commented on simple-chat/src/chat.html
> +                    </div>
Что касается хардкода, стоит так же предусмотреть других пользователей, которых можно задать с помощью кнопки "создать чат"

2024-10-07 14:31 UTC, sh4rkizz commented on simple-chat/src/index.html
> +            <button class="new-msg"><span class="material-symbols-outlined" style="color: #151219;"> edit </span></button>
Здесь в целом ок, но призываю максимально отказываться от инлайн стилей в пользу .css, тк это более корректная практика

2024-10-07 14:32 UTC, sh4rkizz commented
Хотелось бы чтобы кнопка создания чата формировала новый блок на странице чатов [и в него можно было перейти и начать новый чат с человеком]

2024-10-07 14:35 UTC, sh4rkizz commented
Страница чатов довольно сильно ужимает инфу по последним сообщениям из-за больших padding-ов
![изображение](https://github.com/user-attachments/assets/2379ad85-63ee-4a2e-9e1c-d3abef3bf81e)

2024-10-10 10:38 UTC, sh4rkizz approved these changes
давай в рамках 4ой домашки хардкод уберем из ветки

я доволен тем, что я вижу 
модалка отличная, ничего не ломается

2024-10-10 12:54 UTC, merged

2024-10-10 12:54 UTC, martinkomitsky commented
12!