ДЗ_4 на проверку
have2go/2024-2-VK-EDU-Frontend-A-Degtyarev pull request #4
Opened 2024-10-15 11:18 UTC by have2go

# Домашнее задание №4

Прошу @martinkomitsky, @haseprogram, @kgrechin или @sh4rkizz проверить его.

Что было сделано:
* Адаптивная верстка
* Анимации изменения размера, позиции, цвета элементов
* Добавлена страница 404, при попытке вбить через адресную строку некорректный ?chat_id= происходит переадресация на 404

https://github.com/user-attachments/assets/e4745995-e5e9-48b6-a631-15da7914ff22

2024-10-16 09:46 UTC, sh4rkizz requested changes
Давай поправим и будет очень хорошо

2024-10-16 09:46 UTC, sh4rkizz commented on simple-chat/src/index.html
>                  <h1 class="header__title">Список чатов</h1>
Начиная с N-ного [10] элемента списка чатов бэкграунд заканчивается

<img width="844" alt="изображение" src="https://github.com/user-attachments/assets/465f6dc5-5081-4655-9b47-c2f173aac84d">

2024-10-16 09:46 UTC, sh4rkizz commented on simple-chat/src/chat.html
>  <!DOCTYPE html>
Предлагаю убрать автокомплит формы 

<img width="402" alt="изображение" src="https://github.com/user-attachments/assets/2f33301e-2c12-4423-81d8-6c235b32c2c7">

2024-10-16 09:46 UTC, sh4rkizz commented on simple-chat/src/chat.html
>  <!DOCTYPE html>
Стоит так же накинуть trim(), чтобы пустые сообщения не отправлялись
<img width="130" alt="изображение" src="https://github.com/user-attachments/assets/d3745771-5d70-43c6-be28-6727dfd049f1">

2024-10-16 09:46 UTC, sh4rkizz commented on simple-chat/src/chat.html
>  <!DOCTYPE html>
давай ховеры на эти кнопки еще повесим

<img width="676" alt="изображение" src="https://github.com/user-attachments/assets/ecd5a8c6-0759-452e-841a-48e1cc06c110">

<img width="676" alt="изображение" src="https://github.com/user-attachments/assets/cc75c902-7310-4fc3-88e4-0cdf26bb3fc3">

2024-10-16 09:46 UTC, sh4rkizz commented on simple-chat/src/index.js
> +if (chatListArr.messages && chatListArr.at(-1).messages.length === 0) {
поймал ошибку фронта, теперь не могу избавиться от нее)
список чатов, соответственно, сломан

<img width="775" alt="изображение" src="https://github.com/user-attachments/assets/2648d2a1-b0ab-4322-898b-390b0fe386d7">

2024-10-16 13:41 UTC, sh4rkizz approved these changes
домашка огненная, lgtm!

2024-10-19 12:34 UTC, merged

2024-10-19 12:34 UTC, martinkomitsky commented
12!