ДЗ_5 на проверку
have2go/2024-2-VK-EDU-Frontend-A-Degtyarev pull request #5
Opened 2024-10-21 21:56 UTC by have2go

# Домашнее задание №5

Прошу @martinkomitsky, @haseprogram, @kgrechin или @sh4rkizz проверить его.

Что было сделано:
* Приложение переписано на React
* Добавлена анимация появления новых сообщений
* Добавлена возможность закрывать модальное окно нажатием на Esc
* Внедрил Sass, пользовался вложенными селекторами, сокращениями для БЭМ и переменными
* На странице чата теперь скроллбар отображается на краю страницы, а не внутри блока с сообщениями, а также он скрывается во всем приложении для экранов <768px
* Начал добавление возможности смены темы оформления, пока через временную кнопку. Результат по цветам пока не нравится, поэтому я хочу в дальнейшем лучше проработать цвета для каждой роли и скорее всего в целом изменить цветовую гамму (особенно в светлой теме :))

https://github.com/user-attachments/assets/9a2aba03-d0d7-4dd2-9d21-ed6ca9b42857

2024-10-22 16:09 UTC, sh4rkizz requested changes
Предлагаю стилистические доработки, в остальном - очень круто

2024-10-22 16:09 UTC, sh4rkizz commented on react-chat/src/components/NewChatModal/NewChatModal.jsx
> +                <h3 className="newchat__title">Кому вы хотите написать?</h3>
Давай запретим скролл под модалкой 
https://github.com/user-attachments/assets/7c85069a-079f-4a73-83cf-60db5e7b8697

2024-10-22 16:09 UTC, sh4rkizz commented on react-chat/src/components/NewChatModal/NewChatModal.jsx
> +                <h3 className="newchat__title">Кому вы хотите написать?</h3>
Проработаем ховеры [на обеих темах] на кнопках и чатах

![изображение](https://github.com/user-attachments/assets/69f5eb20-0bfa-4594-b749-fcb60ef1f59f)
![изображение](https://github.com/user-attachments/assets/1da146d7-d093-4e02-abdc-264dc1316e83)
![изображение](https://github.com/user-attachments/assets/127de5f8-ee5b-403a-bd1d-6285b79d0b80)

2024-10-22 16:10 UTC, sh4rkizz commented on react-chat/src/components/NewChatModal/NewChatModal.jsx
> +                <h3 className="newchat__title">Кому вы хотите написать?</h3>
Предлагаю тему в localStorage класть и распаковывать в главном компоненте [чтобы перезагрузка страницы не вызывала сброс обратно на темную]

2024-10-22 21:54 UTC, sh4rkizz approved these changes
Огонь! lgtm
В рамках ДЗ-6 договорились сделать закрытие модалки добавления чата по клику не в нее [handleClickOutside]

2024-10-23 18:30 UTC, merged

2024-10-23 18:30 UTC, martinkomitsky commented
12!