ДЗ_6
have2go/2024-2-VK-EDU-Frontend-A-Degtyarev pull request #6
Opened 2024-10-30 12:02 UTC by have2go

# Домашнее задание №6

Прошу @martinkomitsky, @haseprogram, @kgrechin или @sh4rkizz проверить его.

Что было сделано:
* Закрытие модального окна по клику в окружающее пространство
* Запретил зум страницы
* Убраны отступы и скругления для инпута в чате на width <= 768px для лучшего отображения с экранной клавиатурой
* При отправке сообщения в чате оставляется фокус на инпуте
* Пустые чаты теперь не удаляются, остаются в списке с надписью "Нет сообщений"
* Чаты сортируются по дате создания
* Кнопки для смены темы
* Выезжающее бургер-меню (до 1024px)
* Страница профиля
* Сохранение данных о пользователе в localStorage
* Вернул страницу 404
* Создал ProtectedRoute для чата с проверкой ID

https://github.com/user-attachments/assets/9456243e-30f7-4816-b6fb-11480ae27e16

2024-10-30 14:50 UTC, sh4rkizz commented on react-chat/index.html
>      <title>Чат</title>
Думаю с роутингом должны меняться title страниц [сейчас на каждой - "Чат"]

2024-10-30 14:50 UTC, sh4rkizz commented on react-chat/index.html
>      <title>Чат</title>
\+ давай добавим какой-нибудь favicon, чтобы было не так грустно 

<img width="307" alt="изображение" src="https://github.com/user-attachments/assets/ed299b1c-3081-4352-805f-aeb1c0f1e6bc">

2024-10-30 14:50 UTC, sh4rkizz commented on react-chat/src/App.jsx
> +                        </ProtectedRoute>
Предлагаю доработать страничку чата, обработав пустоту 
[когда чат только был создан и нет ни одного сообщения]

<img width="441" alt="изображение" src="https://github.com/user-attachments/assets/623e528c-77ff-452e-857d-b83589d013df">

2024-10-30 14:50 UTC, sh4rkizz commented on react-chat/src/components/NewChatModal/NewChatModal.jsx
>                  <h3 className="newchat__title">Кому вы хотите написать?</h3>
Предлагаю добавить автофокус на поле ввода этой модалки при ее открытии

Убрать возможность перемещаться табами по элементам, которые находятся не внутри модалки. В помощь - https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/inert
[тебе нужно понять куда применить]
 
<img width="337" alt="изображение" src="https://github.com/user-attachments/assets/5b4d84fe-6017-4541-920d-89c3b82ba8ae">

2024-10-30 14:50 UTC, sh4rkizz commented on react-chat/src/pages/Profile/Profile.jsx
> +                <h1 className="header__title">Профиль</h1>
Из-за большого `span` вокруг иконки профиля, кажется что разломаны стили кнопки

<img width="406" alt="изображение" src="https://github.com/user-attachments/assets/000f360c-6e6d-4d35-a1fd-6076d097c099">

2024-10-30 14:50 UTC, sh4rkizz commented on react-chat/src/components/NewChatModal/NewChatModal.jsx
>                  <h3 className="newchat__title">Кому вы хотите написать?</h3>
Давай так же обработаем кнопку Escape, чтобы она закрывала эту модалку

2024-10-30 14:51 UTC, sh4rkizz requested changes
небольшая пачка замечаний + то, что отписал в личку

2024-11-03 09:25 UTC, sh4rkizz approved these changes
lgtm!

2024-11-05 09:18 UTC, martinkomitsky commented
12!

2024-11-05 09:18 UTC, merged