ДЗ_7
have2go/2024-2-VK-EDU-Frontend-A-Degtyarev pull request #7
Opened 2024-11-09 20:10 UTC by have2go

# Домашнее задание №7

Прошу @martinkomitsky, @haseprogram, @kgrechin или @sh4rkizz проверить его.

Что было сделано:
* Сопряжение веб-приложение с бекендом
* Использование websocket с centrifuge для real-time обновления чата
* Новый функционал под эндпоинты: редактирование/удаление сообщений, профиля, чата и т.д.
* Регистрация и авторизация с хранением пользователя в контексте
* Переработано окно создания чата

https://github.com/user-attachments/assets/48286c0c-ef5f-4acc-8700-42a29ab0e4f6

2024-11-12 18:09 UTC, sh4rkizz requested changes

2024-11-12 18:09 UTC, sh4rkizz commented on react-chat/src/pages/Register/Register.jsx
> +            <Helmet>
Давай добавим type="password", чтобы закрыть вводимый пароль
![изображение](https://github.com/user-attachments/assets/0a917ce8-54f6-439b-a8e7-8847e4288412)

2024-11-12 18:09 UTC, sh4rkizz commented on react-chat/src/pages/Register/Register.jsx
> +            <Helmet>
аналогично в логине

![изображение](https://github.com/user-attachments/assets/c7800058-923d-42f9-92d5-4d93ef6b1b20)

2024-11-12 18:09 UTC, sh4rkizz commented on react-chat/src/pages/Register/Register.jsx
> +            <Helmet>
нужно обработать ошибки бекенда на клиенте, должны выводиться красненьким под полем
[авторизация и логин тоже]

![изображение](https://github.com/user-attachments/assets/c5dcf58e-7f83-4be3-b211-5c9d886caeb5)

2024-11-12 18:52 UTC, sh4rkizz commented on react-chat/src/pages/Register/Register.jsx
> +            <Helmet>
![изображение](https://github.com/user-attachments/assets/6fe89486-1676-40b8-8180-8c1638031dce)

2024-11-14 21:28 UTC, sh4rkizz requested changes

2024-11-14 21:28 UTC, sh4rkizz commented on react-chat/src/components/HeaderChat/HeaderChat.jsx
> +                </div>
### Просьба доработать в рамках 8:

Обработка нажатия вне этой кнопки [она должна закрываться]
<img width="246" alt="изображение" src="https://github.com/user-attachments/assets/0d5ed57d-c242-455a-9450-6f811d9681a6">

2024-11-14 21:28 UTC, sh4rkizz commented on react-chat/src/components/HeaderChat/HeaderChat.jsx
> +                </div>
стоит сделать бэкграунд более темным для темной темы у поля ввода

<img width="428" alt="изображение" src="https://github.com/user-attachments/assets/37528400-7f66-411c-a209-33ee4e93f92e">

2024-11-14 21:28 UTC, sh4rkizz commented on react-chat/src/components/HeaderChat/HeaderChat.jsx
> +                </div>
Обработать 400 на создании уже существующего чата

<img width="1190" alt="изображение" src="https://github.com/user-attachments/assets/01e7a3f9-a523-4bcf-9a17-1a9868de1930">

2024-11-14 21:28 UTC, sh4rkizz commented on react-chat/src/components/HeaderChat/HeaderChat.jsx
> +                </div>
### Просьба доработать в рамках 8:

предлагаю добавить lodash.debounce, чтобы не спамить запросами 
https://habr.com/ru/sandbox/182150/

<img width="622" alt="изображение" src="https://github.com/user-attachments/assets/094ebc14-6226-4b5c-b718-fa4fb8a9dfe9">

2024-11-14 21:28 UTC, sh4rkizz commented on react-chat/src/components/HeaderChat/HeaderChat.jsx
> +                </div>
При закрытии этой модалки стоит сбрасывать поиск

<img width="419" alt="изображение" src="https://github.com/user-attachments/assets/21a4a427-c7ad-42ac-858c-4eb799411566">

2024-11-14 21:28 UTC, sh4rkizz commented on react-chat/src/components/HeaderChat/HeaderChat.jsx
> +                </div>
нужно обработать 401 на логин

<img width="1206" alt="изображение" src="https://github.com/user-attachments/assets/52036f48-c0fc-48c8-b85f-d84af6fb5edb">

2024-11-14 21:28 UTC, sh4rkizz commented on react-chat/src/components/HeaderChat/HeaderChat.jsx
> +                </div>
стоит добавить какую-нибудь заполняшку, когда список чатов пустой

<img width="1202" alt="изображение" src="https://github.com/user-attachments/assets/ab292eae-1f35-4cba-8c18-cae86a1aacab">

2024-11-14 21:28 UTC, sh4rkizz commented on react-chat/src/pages/Login/Login.jsx
> +                password: data.password || undefined,
undefined не используй как значение по умолчанию
https://doka.guide/js/undefined/#kak-ponyat

2024-11-14 21:28 UTC, sh4rkizz commented on react-chat/src/pages/Login/Login.jsx
> +                    }
как более простое решение
setErrors({ ...json }), но нужно проверить что json - объект

2024-11-14 21:28 UTC, sh4rkizz commented on react-chat/src/pages/Profile/Profile.jsx
>                  setIsChanged(true);
ты это дело лучше не делай в useEffect, можешь дописать handleChange, добавив необходимую проверку и там же и делать setIsChanged при необходимости

можно же сравнивать `user.data[name] !== data[name]`, 
сейчас - лишний код и лишние перерендеры из-за useEffect

вроде не только в этом месте

2024-11-16 11:49 UTC, sh4rkizz approved these changes
lgtm!

2024-11-19 15:09 UTC, merged

2024-11-19 15:09 UTC, martinkomitsky commented
10!