ДЗ 8
have2go/2024-2-VK-EDU-Frontend-A-Degtyarev pull request #8
Opened 2024-11-18 20:51 UTC by have2go

# Домашнее задание №8

Прошу @martinkomitsky, @haseprogram, @kgrechin или @sh4rkizz проверить его.

Что было сделано:
*

2024-11-18 21:48 UTC, sh4rkizz requested changes

2024-11-18 21:48 UTC, sh4rkizz commented on react-chat/src/components/Message/Message.jsx
> +export const Message = ({ user, msg, selectedMessage, setSelectedMessage }) => {
Хотелось бы счетчик [там 5 файлов]

<img width="351" alt="изображение" src="https://github.com/user-attachments/assets/c430a6de-0053-4f49-b5be-8659d50732ac">

2024-11-18 21:48 UTC, sh4rkizz commented on react-chat/src/components/Message/Message.jsx
> +export const Message = ({ user, msg, selectedMessage, setSelectedMessage }) => {
Хотелось бы красивых модалочек и красивой страницы авторизации-реги

![telegram-cloud-photo-size-2-5321059460489276273-y](https://github.com/user-attachments/assets/9391b03c-0ff1-42b5-a2a7-83d7440f366d)

2024-11-18 21:48 UTC, sh4rkizz commented on react-chat/src/components/Message/Message.jsx
> +export const Message = ({ user, msg, selectedMessage, setSelectedMessage }) => {
Превью аудио немного подломано

![telegram-cloud-photo-size-2-5321059460489276265-x](https://github.com/user-attachments/assets/e4823fa1-b585-480b-82df-4cff154d4353)

2024-11-18 21:48 UTC, sh4rkizz commented on react-chat/src/components/Message/Message.jsx
> +export const Message = ({ user, msg, selectedMessage, setSelectedMessage }) => {
пора сделать обработку пустоты

![telegram-cloud-photo-size-2-5321059460489276259-y](https://github.com/user-attachments/assets/4ae79238-d669-4d01-8e23-0c7181f29d44)

2024-11-18 21:48 UTC, sh4rkizz commented on react-chat/src/components/Message/Message.jsx
> +export const Message = ({ user, msg, selectedMessage, setSelectedMessage }) => {
Предлагаю клик в эту область отслеживать

![telegram-cloud-photo-size-2-5321059460489276283-y](https://github.com/user-attachments/assets/ebe5f4cf-1a6c-4582-a2c2-cc2d5e6c8aa9)

2024-11-18 21:48 UTC, sh4rkizz commented on react-chat/src/components/Message/Message.jsx
> +export const Message = ({ user, msg, selectedMessage, setSelectedMessage }) => {
Давай кроме username сюда отрисовывать еще и фио

![telegram-cloud-photo-size-2-5321059460489276286-y](https://github.com/user-attachments/assets/4f5e01a0-31d6-40e3-a589-bd6be695fffb)

2024-11-18 21:48 UTC, sh4rkizz commented on react-chat/src/components/Message/Message.jsx
> +export const Message = ({ user, msg, selectedMessage, setSelectedMessage }) => {
сейчас не обработана ошибка бекенда, пора приносить toastify

![telegram-cloud-photo-size-2-5321059460489276288-y](https://github.com/user-attachments/assets/3a7ba4e5-bc97-4d33-9a4b-2e2546ec2d88)

2024-11-18 21:48 UTC, sh4rkizz commented on react-chat/src/components/Message/Message.jsx
> +export const Message = ({ user, msg, selectedMessage, setSelectedMessage }) => {
Нахожусь на странице чата, обновляю страницу = выбрасывает на список чатов [нехорошо]
а выбрасывает, потому что 401 запросы почему-то

<img width="494" alt="изображение" src="https://github.com/user-attachments/assets/796c36fe-7145-46ee-bf85-aaab24e1a6cc">

2024-11-18 21:48 UTC, sh4rkizz commented on react-chat/src/components/Message/Message.jsx
> +export const Message = ({ user, msg, selectedMessage, setSelectedMessage }) => {
Ткнул изменить голосовое [отображается что-то странное]
<img width="725" alt="изображение" src="https://github.com/user-attachments/assets/d7688537-28cd-4ccd-9e0a-df2230845677">

2024-11-21 08:00 UTC, sh4rkizz submitted a review, later dismissed
огонь! lgtm

2024-11-21 08:02 UTC, sh4rkizz approved these changes
lgtm [еще раз]

2024-11-24 12:44 UTC, merged

2024-11-24 12:44 UTC, martinkomitsky commented
10!