ДЗ_9
have2go/2024-2-VK-EDU-Frontend-A-Degtyarev pull request #9
Opened 2024-11-21 20:28 UTC by have2go

# Домашнее задание №

Прошу @martinkomitsky, @haseprogram, @kgrechin или @sh4rkizz проверить его.

Что было сделано:
* Подключил Zustand (сторы текущего юзера, чатов, сообщений активного чата, всех юзеров)
* Вынес подписку на центрифугу в App.jsx
* Начал внедрение toastify (сейчас это уведомления из неактивных чатов)

https://github.com/user-attachments/assets/fe99b6c9-c839-4508-8c62-c3a97e4e241c

2024-11-24 10:14 UTC, sh4rkizz requested changes

2024-11-24 10:14 UTC, sh4rkizz commented on react-chat/src/App.jsx
> +    useEffect(() => {
полезно иметь возможность удалить фото здесь

![изображение](https://github.com/user-attachments/assets/320cc587-8e9a-47fa-8dfa-0aec1021bad8)

2024-11-24 10:14 UTC, sh4rkizz commented on react-chat/src/App.jsx
> +    useEffect(() => {
Предлагаю добавить лоадер

когда находишься в чате A, выходишь назад, переходишь к чату Б
на долю секунды видишь сообщения из чата А, после чего они ререндерятся

2024-11-24 10:14 UTC, sh4rkizz commented on react-chat/src/App.jsx
> +    useEffect(() => {
Поскольку тостифай вкручен можно избавиться от алертов
![изображение](https://github.com/user-attachments/assets/563fc562-2647-4be6-ba8d-9431efb9ef38)

2024-11-24 10:14 UTC, sh4rkizz commented on react-chat/src/App.jsx
> +    useEffect(() => {
На мобилке клавиатура прыгает при отправке сообщения

2024-11-24 10:15 UTC, sh4rkizz commented on react-chat/src/App.jsx
> +    useEffect(() => {
аналогично про тостифай

![изображение](https://github.com/user-attachments/assets/b78a9478-03d6-4ee3-8cff-292990c524c4)

2024-11-24 10:18 UTC, sh4rkizz commented on react-chat/src/App.jsx
> +    useEffect(() => {
при выборе "своего" сообщения появляются эти иконки
![изображение](https://github.com/user-attachments/assets/6cc0663b-716a-4296-bb6b-2323e07809fe)

при выборе сообщения собеседника кнопки в шапке не меняются [можно случайно дропнуть чат]
![изображение](https://github.com/user-attachments/assets/5c87d7b7-240a-4758-ae1b-a4663cc78f72)

не понятно что дает возможность выбора сообщения собеседника, но если планируется какая-то доработка в этой области, то стоит менять набор кнопок в шапке [пусть даже на пустой]

2024-11-25 21:39 UTC, sh4rkizz submitted a review, later dismissed
огонь ваще!
lgtm

2024-11-25 21:39 UTC, sh4rkizz approved these changes
очень круто получается

2024-11-26 21:50 UTC, HaseProgram commented
Супер! 12

2024-11-26 21:50 UTC, merged